### ISSUE TITLE
Hike tracking

### ISSUE THREAD

**Issue by dadegrande99** [dadegrande99/HikeMap#10]
Implement the management of hike data

- [ ] data tracking
- [x] saving to database

The data to be managed are about:

- [x] Timing
- [ ] Miles traveled
- [ ] Uphill elevation gain
- [ ] Downhill elevation loss
- [x] #21
